---
- name: "Ensure dependencies are installed"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ mysql_install['dependencies']['RedHat'] }}"

- name: "Add repo for RedHat"
  block:
    - name: "Import MySQL gpg key"
      ansible.builtin.rpm_key:
        key: "{{ mysql_const[ansible_os_family][mysql.repo]['gpg'] }}"
        state: present

    - name: "Add MySQL repository"
      ansible.builtin.yum_repository:
        name: mysql
        description: mysql YUM repo
        baseurl: "{{ mysql_const[ansible_os_family][mysql.repo]['repo'] }}"
        gpgcheck: yes
        enabled: true
        module_hotfixes: true
  when: mysql.repo == "mysql"

- name: "Install mysql packages"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: true
  ignore_errors: true
  register: mysql_install_redhat
  with_items: "{{ mysql_install['packages']['RedHat'] }}"

- name: "-> 02_mysql_reset_root_password.yml"
  include_tasks: ./tasks/02_mysql_reset_root_password.yml
  when: mysql_install_redhat.changed and mysql.repo == "mysql"