---
- name: "Ensure dependencies are installed"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ mysql_const[ansible_os_family]['dependencies'] }}"

- name: "Add repo MySQL"
  block:
    - name: "Add repository gpg key"
      ansible.builtin.apt_key:
        id: "{{ mysql_const[ansible_os_family][mysql.repo]['gpg'] }}"
        keyserver: keyserver.ubuntu.com
        state: present

    - name: "Add MySQL repository"
      ansible.builtin.apt_repository:
        repo: "{{ mysql_const[ansible_os_family][mysql.repo]['repo'] }}"
        state: present
  when: mysql.repo == "mysql"

- name: "Install MySQL packages"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ mysql_const[ansible_os_family]['packages'] }}"