---
- name: "Service facts"
  ansible.builtin.service_facts:

- name: "Add skip-grant-tables to config"
  ansible.builtin.lineinfile:
    path: "{{ mysql_const[ansible_os_family]['config_path'] }}{{ mysql_const[ansible_os_family]['config_file'] }}"
    line: "skip-grant-tables"
    state: present
    regexp: '^skip-grant-tables'

- name: "Restart MySQL"
  ansible.builtin.service:
    name: "{{ mysql_const[ansible_os_family]['service_name'] }}"
    state: restarted
    enabled: "{{ mysql.service.enabled }}"
  when: ansible_facts.services is search("mysqld")

- name: "Remove root password"
  ansible.builtin.raw: mysql -e "UPDATE mysql.user SET authentication_string='' WHERE user='root';" -uroot

- name: "Remove skip-grant-tables in config"
  ansible.builtin.lineinfile:
    path: "{{ mysql_const[ansible_os_family]['config_path'] }}{{ mysql_const[ansible_os_family]['config_file'] }}"
    line: "skip-grant-tables"
    state: absent
    regexp: '^skip-grant-tables'

- name: "Restart MySQL"
  ansible.builtin.service:
    name: "{{ mysql_const[ansible_os_family]['service_name'] }}"
    state: restarted
    enabled: "{{ mysql.service.enabled }}"
  when: ansible_facts.services is search("mysqld")

- name: "Set temp difficult password"
  shell: mysql -e "SET PASSWORD = 'Temp_difficult_password1=';" --connect-expired-password -uroot

- name: "Uninstall component_validate_password"
  shell: mysql -e "UNINSTALL COMPONENT 'file://component_validate_password';" -uroot -p'Temp_difficult_password1='

- name: "Clear root password completly"
  shell: mysql -e "SET PASSWORD = '';" -uroot -p'Temp_difficult_password1='
