---
- name: "Merge dictionaries"
  block:
    - name: "Register default vars"
      include_vars:
        file: ../../darexsu.mysql/defaults/main.yml
        name: mysql_default_vars

    - name: "Merge default and new dictionaries"
      set_fact:
        "{{ item.key }}": "{{ mysql_default_vars[item.key] | combine(merge[item.key], recursive=True)}}"
      when: mysql_default_vars[item.key] is defined
      with_dict: "{{ merge }}"

    - name: "Combine defaults vars with merge dictionary"
      set_fact:
        merge: "{{ mysql_default_vars | combine(merge, recursive=True)}}"
  when: merge is defined

- name: "MySQL role is disabled"
  meta: end_play
  when: not mysql.enabled

- name: "-> 01_mysql_install_{{ ansible_os_family }}.yml"
  include_tasks: ./tasks/01_mysql_install_{{ ansible_os_family }}.yml
  when: mysql_install.enabled

- name: "Service facts"
  ansible.builtin.service_facts:

- name: "-> 03_mysql_config.yml"
  include_tasks: ./tasks/03_mysql_config.yml
  when: ansible_facts.services is search("mysql") and mysql_config.enabled

- name: "Ensure MySQL {{ mysql.service.state }}"
  ansible.builtin.service:
    name: "{{ mysql_const[ansible_os_family]['service_name'] }}"
    state: "{{ mysql.service.state }}"
    enabled: "{{ mysql.service.enabled }}"
  when: ansible_facts.services is search("mysql")