---
- name: merge dictionaries
  block:
  - include_vars:
      file: ../../darexsu.mysql/defaults/main.yml
      name: mysql_default_vars

  - name: merge default and new dictionaries
    set_fact:
      "{{ item.key }}": "{{ mysql_default_vars[item.key] | combine(merge[item.key], recursive=True)}}"
    when: mysql_default_vars[item.key] is defined
    with_dict: "{{ merge }}"

  - name: combine defaults vars with merge dictionary
    set_fact:
      merge: "{{ mysql_default_vars | combine(merge, recursive=True)}}"
  when: merge is defined

- name: mysql role is disabled
  meta: end_play
  when: not mysql.enabled

- name: include mysql install
  include_tasks: ./tasks/install/mysql_install__{{ ansible_os_family }}.yml
  when: mysql_install.enabled

- name: include mysql config
  include_tasks: ./tasks/config/mysql_config.yml
  when: mysql_config.enabled

- name: service facts
  ansible.builtin.service_facts:

- name: "ensure mysql {{ mysql.service.state }}"
  ansible.builtin.service:
    name: "{{ mysql_const[ansible_os_family]['service_name'] }}"
    state: "{{ mysql.service.state }}"
    enabled: "{{ mysql.service.enabled }}"
  when: ansible_facts.services is search("mysql")