---
- name: service facts
  ansible.builtin.service_facts:

- name: "ensure mysql started"
  ansible.builtin.service:
    name: "{{ mysql_const[ansible_os_family]['service_name'] }}"
    state: started
    enabled: "{{ mysql.service.enabled }}"
  when: ansible_facts.services is search("mysqld")

- name: find mysql log
  ansible.builtin.slurp:
    src: "/var/log/mysqld.log"
  register: mysql_log

- name: filter temp password
  ansible.builtin.set_fact:
    mysql_temp_root_password: "{{ mysql_log['content'] | b64decode |  regex_search('(?<=root@localhost: )(.*)(?=\n)') }}"

- name: set new password from temporary password
  shell: mysql -e "SET PASSWORD = '{{ mysql_temp_root_password }}';" --connect-expired-password -uroot -p'{{ mysql_temp_root_password }}'

- name: uninstall validate password
  shell: mysql -e "UNINSTALL COMPONENT 'file://component_validate_password';" --connect-expired-password -uroot -p'{{ mysql_temp_root_password }}'

- name: "ensure mysql restarted"
  ansible.builtin.service:
    name: "{{ mysql_const[ansible_os_family]['service_name'] }}"
    state: restarted
    enabled: "{{ mysql.service.enabled }}"
  when: ansible_facts.services is search("mysqld")

- name: clear root password
  shell: mysql -e "SET PASSWORD = '';" --connect-expired-password -uroot -p'{{ mysql_temp_root_password }}'