---
- name: service facts
  ansible.builtin.service_facts:

- name: add skip-grant-tables to config
  ansible.builtin.lineinfile:
    path: "{{ mysql_const[ansible_os_family]['config_path'] }}{{ mysql_const[ansible_os_family]['config_file'] }}"
    line: "skip-grant-tables"
    state: present
    regexp: '^skip-grant-tables'

- name: restart mysql
  ansible.builtin.service:
    name: "{{ mysql_const[ansible_os_family]['service_name'] }}"
    state: restarted
    enabled: "{{ mysql.service.enabled }}"
  when: ansible_facts.services is search("mysqld")

- name: remove root password
  ansible.builtin.raw: mysql -e "UPDATE mysql.user SET authentication_string='' WHERE user='root';" -uroot
  args:
    executable: /bin/bash

- name: remove skip-grant-tables in config
  ansible.builtin.lineinfile:
    path: "{{ mysql_const[ansible_os_family]['config_path'] }}{{ mysql_const[ansible_os_family]['config_file'] }}"
    line: "skip-grant-tables"
    state: absent
    regexp: '^skip-grant-tables'

- name: restart mysql
  ansible.builtin.service:
    name: "{{ mysql_const[ansible_os_family]['service_name'] }}"
    state: restarted
    enabled: "{{ mysql.service.enabled }}"
  when: ansible_facts.services is search("mysqld")

- name: set temp difficult password
  shell: mysql -e "SET PASSWORD = 'Temp_difficult_password1=';" --connect-expired-password -uroot

- name: uninstall component_validate_password
  shell: mysql -e "UNINSTALL COMPONENT 'file://component_validate_password';" -uroot -p'Temp_difficult_password1='

- name: clear root password completly
  shell: mysql -e "SET PASSWORD = '';" -uroot -p'Temp_difficult_password1='

- name: zabbix user
  community.mysql.mysql_user:
    login_user: 'root'
    login_password: ''
    login_host: "localhost"
    login_unix_socket: "/var/lib/mysql/mysql.sock"
    name: "asdasd"
    password: "asdh456756!asd"
    state: "present"