---
- name: service facts
  ansible.builtin.service_facts:

- name: "ensure mysql started"
  ansible.builtin.service:
    name: "{{ mysql_const[ansible_os_family]['service_name'] }}"
    state: started
    enabled: "{{ mysql.service.enabled }}"
  when: ansible_facts.services is search("mysqld")

- name: find mysql log
  ansible.builtin.slurp:
    src: "/var/log/mysqld.log"
  register: mysql_log


- name:
  debug:
    var: mysql_log


- shell: cat /var/log/mysqld.log | grep "temporary password" | grep -oE '[^ ]+$'
  register: mysql_temp_root_password

- name: set new password from temporary password
  shell: mysql -e "SET PASSWORD = '{{ mysql_temp_root_password.stdout }}';" --connect-expired-password -uroot -p'{{ mysql_temp_root_password.stdout }}'

- name: uninstall validate password
  shell: mysql -e "UNINSTALL COMPONENT 'file://component_validate_password';" --connect-expired-password -uroot -p'{{ mysql_temp_root_password.stdout }}'

- name: "ensure mysql restarted"
  ansible.builtin.service:
    name: "{{ mysql_const[ansible_os_family]['service_name'] }}"
    state: restarted
    enabled: "{{ mysql.service.enabled }}"
  when: ansible_facts.services is search("mysqld")

- name: clear root password
  shell: mysql -e "SET PASSWORD = '';" --connect-expired-password -uroot -p'{{ mysql_temp_root_password.stdout }}'