---
- name: Converge
  hosts: all
  become: yes

  pre_tasks:
  - name: Unnessessary command
    ansible.builtin.shell:
      cmd: "{{ lookup('env', 'ANSIBLE_COMMAND') }}"
    when: lookup('env', 'ANSIBLE_COMMAND') | length > 0

  vars:
    merge:
      # MySQL
      mysql:
        enabled: true
        repo: "mysql"
        version: "8.0"
        service:
          state: "started"
          enabled: true

      # MySQL -> install
      mysql_install:
        enabled: true
        packages:
          Debian: [mysql-server]
          RedHat: [mysql-server]
        dependencies:
          Debian: [gnupg2, python3, python3-pymysql]
          RedHat: [python3, python3-PyMySQL]

      # MySQL -> config
      mysql_config:
        enabled: true
        file: "{{ mysql_const[ansible_os_family]['config_file']}}"
        src: "mysql_server.conf.j2"
        backup: false
        skip-grant-tables: false
        data:
          pid-file: "{{ mysql_const[ansible_os_family]['pid-file'] }}"
          socket: "{{ mysql_const[ansible_os_family]['socket'] }}"
          datadir: "{{ mysql_const[ansible_os_family]['datadir'] }}"
          log-error: "{{ mysql_const[ansible_os_family][mysql.repo]['log-error'] }}"

  tasks:
    - name: include role mysql
      include_role:
        name: darexsu.mysql
