---
- name: Converge
  hosts: all

  pre_tasks:
  - name: Unnessessary command
    ansible.builtin.shell:
      cmd: "{{ lookup('env', 'ANSIBLE_COMMAND') }}"
    when: lookup('env', 'ANSIBLE_COMMAND') | length > 0

  vars:
    merge:
    # ┌┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄             mysql
      mysql:
        enabled: true
        src: "third_party"
        version: ""
        service:
          state: "started"
          enabled: true
    # ┌┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄             remove mysql
      mysql_remove:
        enabled: true
    # ┌┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄             install mysql
      mysql_install:
        enabled: true
    # ┌┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄             config server.cnf
      mysql_config:
        enabled: true
        file: "{{ mysql_const[ansible_os_family]['config_file']}}"
        src: "mysql__server.conf.j2"
        backup: true
        skip-grant-tables: true
        vars:
          pid-file: "{{ mysql_const[ansible_os_family]['pid-file'] }}"
          socket: "{{ mysql_const[ansible_os_family]['socket'] }}"
          datadir: "{{ mysql_const[ansible_os_family]['datadir'] }}"
          log-error: "{{ mysql_const[ansible_os_family]['log-error'] }}"

  tasks:
    - name: include role mysql
      include_role:
        name: darexsu.mysql
